# Generated by Django 2.1.7 on 2019-02-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='address',
            new_name='userAddress',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='search_for',
            new_name='userConcern',
        ),
    ]
